[2025-10-21T18:53:59.669+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_scd2.run_processor_extract_HSE manual__2025-10-21T18:53:47.554838+00:00 [queued]>
[2025-10-21T18:53:59.754+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_scd2.run_processor_extract_HSE manual__2025-10-21T18:53:47.554838+00:00 [queued]>
[2025-10-21T18:53:59.773+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-21T18:53:59.965+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_processor_extract_HSE> on 2025-10-21 18:53:47.554838+00:00
[2025-10-21T18:54:00.170+0000] {standard_task_runner.py:60} INFO - Started process 7169 to run task
[2025-10-21T18:54:00.222+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_scd2', 'run_processor_extract_HSE', 'manual__2025-10-21T18:53:47.554838+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/process_scripts.py', '--cfg-path', '/tmp/tmpp23ow4iy']
[2025-10-21T18:54:00.246+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask run_processor_extract_HSE
[2025-10-21T18:54:00.440+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-21T18:54:00.942+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_scd2.run_processor_extract_HSE manual__2025-10-21T18:53:47.554838+00:00 [running]> on host 436d1e220711
[2025-10-21T18:54:01.297+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_scd2' AIRFLOW_CTX_TASK_ID='run_processor_extract_HSE' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T18:53:47.554838+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T18:53:47.554838+00:00'
[2025-10-21T18:54:01.324+0000] {logging_mixin.py:188} INFO - Exécution du script : /opt/***/scripts/processor_extract_HSE.py
[2025-10-21T18:54:09.142+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process_scripts.py", line 46, in run_script
    raise Exception(
Exception: Script /opt/***/scripts/processor_extract_HSE.py failed
STDOUT:

STDERR:
Traceback (most recent call last):
  File "/opt/***/scripts/processor_extract_HSE.py", line 192, in <module>
    res = extract_hse_invariants(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/***/scripts/processor_extract_HSE.py", line 119, in extract_hse_invariants
    raise FileNotFoundError("Aucun fichier contenant 'extraction' trouvé dans le répertoire input.")
FileNotFoundError: Aucun fichier contenant 'extraction' trouvé dans le répertoire input.

[2025-10-21T18:54:09.393+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_pipeline_scd2, task_id=run_processor_extract_HSE, execution_date=20251021T185347, start_date=20251021T185359, end_date=20251021T185409
[2025-10-21T18:54:09.559+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 90 for task run_processor_extract_HSE (Script /opt/***/scripts/processor_extract_HSE.py failed
STDOUT:

STDERR:
Traceback (most recent call last):
  File "/opt/***/scripts/processor_extract_HSE.py", line 192, in <module>
    res = extract_hse_invariants(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/***/scripts/processor_extract_HSE.py", line 119, in extract_hse_invariants
    raise FileNotFoundError("Aucun fichier contenant 'extraction' trouvé dans le répertoire input.")
FileNotFoundError: Aucun fichier contenant 'extraction' trouvé dans le répertoire input.
; 7169)
[2025-10-21T18:54:09.670+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-21T18:54:09.978+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
