[2025-10-05T21:00:51.701+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_scd2.load_to_dw_scd2 manual__2025-10-05T20:57:02.587799+00:00 [queued]>
[2025-10-05T21:00:51.718+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_scd2.load_to_dw_scd2 manual__2025-10-05T20:57:02.587799+00:00 [queued]>
[2025-10-05T21:00:51.719+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-05T21:00:51.765+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_dw_scd2> on 2025-10-05 20:57:02.587799+00:00
[2025-10-05T21:00:51.781+0000] {standard_task_runner.py:60} INFO - Started process 1001 to run task
[2025-10-05T21:00:51.797+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_scd2', 'load_to_dw_scd2', 'manual__2025-10-05T20:57:02.587799+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/process_scripts.py', '--cfg-path', '/tmp/tmpwpfq62od']
[2025-10-05T21:00:51.805+0000] {standard_task_runner.py:88} INFO - Job 155: Subtask load_to_dw_scd2
[2025-10-05T21:00:51.873+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-05T21:00:52.093+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_scd2.load_to_dw_scd2 manual__2025-10-05T20:57:02.587799+00:00 [running]> on host 61b2e37950d0
[2025-10-05T21:00:52.267+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_scd2' AIRFLOW_CTX_TASK_ID='load_to_dw_scd2' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T20:57:02.587799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-05T20:57:02.587799+00:00'
[2025-10-05T21:00:52.291+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process_scripts.py", line 27, in run_scd2_loader
    from plugins.scd2_loader import load_all_out_files_to_dw
ModuleNotFoundError: No module named 'plugins'
[2025-10-05T21:00:52.316+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_pipeline_scd2, task_id=load_to_dw_scd2, execution_date=20251005T205702, start_date=20251005T210051, end_date=20251005T210052
[2025-10-05T21:00:52.346+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 155 for task load_to_dw_scd2 (No module named 'plugins'; 1001)
[2025-10-05T21:00:52.371+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-05T21:00:52.394+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
