[2025-10-21T18:12:51.056+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_scd2.run_processor_extract_HSE manual__2025-10-21T18:12:45.999746+00:00 [queued]>
[2025-10-21T18:12:51.093+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_scd2.run_processor_extract_HSE manual__2025-10-21T18:12:45.999746+00:00 [queued]>
[2025-10-21T18:12:51.094+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-21T18:12:51.198+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_processor_extract_HSE> on 2025-10-21 18:12:45.999746+00:00
[2025-10-21T18:12:51.214+0000] {standard_task_runner.py:60} INFO - Started process 6610 to run task
[2025-10-21T18:12:51.221+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_scd2', 'run_processor_extract_HSE', 'manual__2025-10-21T18:12:45.999746+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/process_scripts.py', '--cfg-path', '/tmp/tmp2zkcwck1']
[2025-10-21T18:12:51.225+0000] {standard_task_runner.py:88} INFO - Job 81: Subtask run_processor_extract_HSE
[2025-10-21T18:12:51.272+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-21T18:12:51.428+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_scd2.run_processor_extract_HSE manual__2025-10-21T18:12:45.999746+00:00 [running]> on host 436d1e220711
[2025-10-21T18:12:51.669+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_scd2' AIRFLOW_CTX_TASK_ID='run_processor_extract_HSE' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T18:12:45.999746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T18:12:45.999746+00:00'
[2025-10-21T18:12:51.674+0000] {logging_mixin.py:188} INFO - Exécution du script : /opt/***/scripts/processor_extract_HSE.py
[2025-10-21T18:12:56.380+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process_scripts.py", line 46, in run_script
    raise Exception(
Exception: Script /opt/***/scripts/processor_extract_HSE.py failed
STDOUT:

STDERR:
Traceback (most recent call last):
  File "/opt/***/scripts/processor_extract_HSE.py", line 192, in <module>
    res = extract_hse_invariants(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/***/scripts/processor_extract_HSE.py", line 119, in extract_hse_invariants
    raise FileNotFoundError("Aucun fichier contenant 'extraction' trouvé dans le répertoire input.")
FileNotFoundError: Aucun fichier contenant 'extraction' trouvé dans le répertoire input.

[2025-10-21T18:12:56.422+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_pipeline_scd2, task_id=run_processor_extract_HSE, execution_date=20251021T181245, start_date=20251021T181251, end_date=20251021T181256
[2025-10-21T18:12:56.488+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 81 for task run_processor_extract_HSE (Script /opt/***/scripts/processor_extract_HSE.py failed
STDOUT:

STDERR:
Traceback (most recent call last):
  File "/opt/***/scripts/processor_extract_HSE.py", line 192, in <module>
    res = extract_hse_invariants(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/***/scripts/processor_extract_HSE.py", line 119, in extract_hse_invariants
    raise FileNotFoundError("Aucun fichier contenant 'extraction' trouvé dans le répertoire input.")
FileNotFoundError: Aucun fichier contenant 'extraction' trouvé dans le répertoire input.
; 6610)
[2025-10-21T18:12:56.523+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-21T18:12:56.598+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
