[2025-10-09T18:12:09.345+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: etl_pipeline_scd2.ERIS_Report_Extraction_31_07_2025_processor_extract_HSE manual__2025-10-09T18:12:06.612102+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
