[2025-10-23T21:31:59.842+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_scd2.run_processor_extract_ep11 manual__2025-10-23T21:29:42.599425+00:00 [queued]>
[2025-10-23T21:31:59.878+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_scd2.run_processor_extract_ep11 manual__2025-10-23T21:29:42.599425+00:00 [queued]>
[2025-10-23T21:31:59.880+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-23T21:31:59.976+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_processor_extract_ep11> on 2025-10-23 21:29:42.599425+00:00
[2025-10-23T21:32:00.079+0000] {standard_task_runner.py:60} INFO - Started process 1169 to run task
[2025-10-23T21:32:00.157+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_scd2', 'run_processor_extract_ep11', 'manual__2025-10-23T21:29:42.599425+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/process_scripts.py', '--cfg-path', '/tmp/tmplrjc53jk']
[2025-10-23T21:32:00.235+0000] {standard_task_runner.py:88} INFO - Job 133: Subtask run_processor_extract_ep11
[2025-10-23T21:32:00.511+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-23T21:32:01.959+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_scd2.run_processor_extract_ep11 manual__2025-10-23T21:29:42.599425+00:00 [running]> on host ca755dafa923
[2025-10-23T21:32:04.075+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_scd2' AIRFLOW_CTX_TASK_ID='run_processor_extract_ep11' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T21:29:42.599425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T21:29:42.599425+00:00'
[2025-10-23T21:32:04.261+0000] {logging_mixin.py:188} INFO - Exécution du script : /opt/***/scripts/processor_extract_ep11.py
[2025-10-23T21:32:16.080+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process_scripts.py", line 43, in run_script
    raise Exception(
Exception: Script /opt/***/scripts/processor_extract_ep11.py failed
STDOUT:
❌ Aucun fichier Invariant study trouvé dans data/out

STDERR:

[2025-10-23T21:32:16.519+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_pipeline_scd2, task_id=run_processor_extract_ep11, execution_date=20251023T212942, start_date=20251023T213159, end_date=20251023T213216
[2025-10-23T21:32:19.139+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 133 for task run_processor_extract_ep11 (Script /opt/***/scripts/processor_extract_ep11.py failed
STDOUT:
❌ Aucun fichier Invariant study trouvé dans data/out

STDERR:
; 1169)
[2025-10-23T21:32:19.602+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-23T21:32:20.008+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
